import { defineConfig } from 'cspell'

export default defineConfig({
  words: [
    'azat',
    'bridgecrewio',
    'changelogen',
    'changelogithub',
    'cmder',
    'commitish',
    'crosspost',
    'gitea',
    'humanwhocodes',
    'oauthtoken',
    'octocat',
    'premajor',
    'preminor',
    'prepatch',
    'pinact',
    'pipefail',
    'rcompare',
    'rolldown',
    'segs',
    'worktree',
    'xlarge',
    'zipball',
  ],
  ignorePaths: [
    '.github',
    '__screens__',
    'changelog.md',
    'license',
    'pnpm-lock.yaml',
    'tsconfig.json',
  ],
  dictionaries: ['css', 'html', 'node', 'npm', 'typescript'],
  useGitignore: true,
  language: 'en',
})
